--- 
version: "3"
services: 
  books: 
    build: ./books
    ports:
    - '8080:8080'
  customers: 
    build: ./customers
    ports:
    - '8081:8081'
  orders: 
    build: ./orders
    ports:
    - '8082:8082'
